version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"  
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  
    depends_on:
      - app  

  app:
    build:
      context: ./app  
      dockerfile: Dockerfile
    deploy:
      replicas: 2  
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydb  
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_REDIS_HOST=redis 
      - SPRING_REDIS_PORT=6379
    depends_on:
      - postgres  
      - redis 

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432" 
    networks:
      - backend 

  redis:
    image: redis:latest
    ports:
      - "6379:6379" 
    networks:
      - backend  

networks:
  backend:  
    driver: bridge 
